dependencies:
  - python=3.7
  - scipy
  - numpy
  - pip
  - pip:
      # environment dependencies
      - aenum==3.1.5
      - networkx==2.6.3
      - triangle==20220202
      - Polygon3==3.0.9.1
      - pybind11==2.9.0
      - setuptools==50.3.2
      # learning dependencies
      - gym==0.21.0
      # CommonRoad packages
      - commonroad-io==2021.1
      - commonroad-vehicle-models
      # Evaluation dependencies
      - SALib==1.3.13
      # parser for setup.py
      - pyparsing==2.4.7
      # for inverse constraint RL
      - wandb==0.10.12
      - torch==1.5.0
      - matplotlib==3.3.2
      - cloudpickle==1.2.2
      - tqdm
      - pandas
      - pillow
      - psutil
      - mpl-scatter-density
      - imageio
      - pickle5
      - patchelf
