conda env create -n cr37 -f environment.ymlname: cr37

dependencies:
  - python=3.7
  - tensorflow=1.15.0
  - scipy
  - numpy==1.21.1
  - pip=20.2.4
  - pip:
      # environment dependencies
      - aenum
      - networkx
      - triangle
      - Polygon3
      - pybind11
      - setuptools==50.3.2
      # learning dependencies
      - gym
      - stable_baselines
      # CommonRoad packages
      - commonroad-io==2021.1
      - commonroad-vehicle-models
      # Evaluation dependencies
      - SALib==1.3.13
      # parser for setup.py
      - pyparsing==2.4.7
      # for inverse constraint RL
      - wandb==0.10.12
      - torch==1.5.0
      - matplotlib==3.3.2
      - cloudpickle==1.2.2
      - tqdm
      - pandas
      - pillow
      - psutil
      - mpl-scatter-density

