task: 'GAIL-HC'
group: 'GAIL'
device: 'cuda'
verbose: 2
env:
  config_path: null
  train_env_id : 'HCWithPos-v0'
  eval_env_id: 'HCWithPos-v0'  # 'HCWithPosTest-v0'
  save_dir: '../save_model'
  cost_info_str: 'cost'
  use_cost: True
  reward_gamma: 0.99
  cost_gamma: 0.99  # no cost
  dont_normalize_obs: False
  dont_normalize_reward: False
  record_info_names: ["xpos"]
  record_info_input_dims: [0] # the dim of record info in inputs=(obs, action)
  visualize_info_ranges: [[-30, 30]]

running:
  save_every: 500000
  expert_rollouts: 10
  expert_path: '../data/expert_data/HCWithPos-New/'

PPO:
  policy_name: 'MlpPolicy'
  learning_rate: 0.0003
  n_steps: 2048
  n_epochs: 10
  reward_gamma: 0.99
  reward_gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  reward_vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: -1
  target_kl: 0.01
  shared_layers: null
  policy_layers: [64, 64]
  reward_vf_layers: [64, 64]
  batch_size: 64
  eval_every: 2048
  timesteps: 4000000

DISC:
  disc_acs_select_dim: null
  disc_batch_size: null
  disc_eps: 1e-05
  disc_layers: [ 30 ]
  disc_learning_rate: 0.003
  disc_normalize": false
  disc_obs_select_dim": null
  disc_plot_every": 1