task: 'PI-Lag-WallGrid'
group: 'PI-Lag'
device: 'cuda'
verbose: 2
env:
  config_path: '../mujuco_environment/custom_envs/envs/configs/mixture_WGW-v0.yaml'
  train_env_id : 'WGW-v0'
  eval_env_id: 'WGW-v0'
  constraint_id: 0  # the id of constraint, 0: the first constraint, 2: the second constraint, null: dynamic constraints
  save_dir: '../save_model'
  cost_info_str: 'cost'
  use_cost: True
  reward_gamma: 0.99
  cost_gamma: 0.99  # no cost
  dont_normalize_obs: True
  dont_normalize_reward: True
  dont_normalize_cost: True  # cost
  record_info_names: ['x_position', 'y_position']
  record_info_input_dims: [ 0, 1 ] # the dim of record info in inputs=(obs, action)
  visualize_info_ranges: [ [ 0, 6 ], [ 0, 6 ]  ]

running:
  n_iters: 1
  n_eval_episodes: 10
  save_every: 1
  latent_dim: 2
  render: False

interation:
  stopping_threshold: 0.001
  max_iter: 100
  penalty_initial_value: 0.1
  penalty_learning_rate: 0.1
  gamma: 0.7
